//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDBF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDetails", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    [System.SerializableAttribute()]
    public partial class CardDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfReaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerNo {
            get {
                return this.ControllerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNoField, value) != true)) {
                    this.ControllerNoField = value;
                    this.RaisePropertyChanged("ControllerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Expiry {
            get {
                return this.ExpiryField;
            }
            set {
                if ((this.ExpiryField.Equals(value) != true)) {
                    this.ExpiryField = value;
                    this.RaisePropertyChanged("Expiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfReader {
            get {
                return this.NoOfReaderField;
            }
            set {
                if ((this.NoOfReaderField.Equals(value) != true)) {
                    this.NoOfReaderField = value;
                    this.RaisePropertyChanged("NoOfReader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardStatus", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    [System.SerializableAttribute()]
    public partial class CardStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EntityFrameworkDBF.ServiceReference1.Card_Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityFrameworkDBF.ServiceReference1.Card_Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card_Status", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    public enum Card_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardActivated = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedToActivateCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardDeactivated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedToDeactivateCard = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateStatus", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    [System.SerializableAttribute()]
    public partial class TemplateStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EntityFrameworkDBF.ServiceReference1.Template_Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EntityFrameworkDBF.ServiceReference1.Template_Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template_Status", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    public enum Template_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateDownloaded = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedToDownloadTemplate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateUploaded = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedToUploadTemplate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotActivated = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceActivateCardClass", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    [System.SerializableAttribute()]
    public partial class DeviceActivateCardClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivateStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivateStatus {
            get {
                return this.ActivateStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivateStatusField, value) != true)) {
                    this.ActivateStatusField = value;
                    this.RaisePropertyChanged("ActivateStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName {
            get {
                return this.ControllerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true)) {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expiry {
            get {
                return this.ExpiryField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryField, value) != true)) {
                    this.ExpiryField = value;
                    this.RaisePropertyChanged("Expiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enroll_Error_Code", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    public enum Enroll_Error_Code : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Found_Code_98 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Not_Found_Code_105 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Id_Exists_110 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Not_Match_Code_106 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Communication_Time_Out_Code_241 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Scan_Fail_Code_99 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Please_Try_Again_Code_107 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Time_Out_108 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_ID__Code_118 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bio_Cancelled_Code_129 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duress_Finger_Code_145 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Match_Timeout_Code_122 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bio_Continue_Code_116 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User_Enrolled_Successfully_Code_97 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Memory_Full_Code_109 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Limit_Reached_Code_114 = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Device_Busy_Code_128 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finger_Exists_Code_134 = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bio_Timeout_Code_156 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No_Finger_Space_Code_117 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined_Code_108 = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Command_e_000 = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success_Command_Code_001 = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Socket_Timed_out = 23,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionTable", Namespace="http://schemas.datacontract.org/2004/07/SmartServiceModel")]
    [System.SerializableAttribute()]
    public partial class TransactionTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ControllerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeFunctionCardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventMsgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IOEntryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReadPointerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReaderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReaderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ControllerID {
            get {
                return this.ControllerIDField;
            }
            set {
                if ((this.ControllerIDField.Equals(value) != true)) {
                    this.ControllerIDField = value;
                    this.RaisePropertyChanged("ControllerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCode {
            get {
                return this.EmployeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeCodeField, value) != true)) {
                    this.EmployeeCodeField = value;
                    this.RaisePropertyChanged("EmployeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeFunctionCardID {
            get {
                return this.EmployeeFunctionCardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeFunctionCardIDField, value) != true)) {
                    this.EmployeeFunctionCardIDField = value;
                    this.RaisePropertyChanged("EmployeeFunctionCardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventCode {
            get {
                return this.EventCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventCodeField, value) != true)) {
                    this.EventCodeField = value;
                    this.RaisePropertyChanged("EventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventMsgName {
            get {
                return this.EventMsgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventMsgNameField, value) != true)) {
                    this.EventMsgNameField = value;
                    this.RaisePropertyChanged("EventMsgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IOEntryStatus {
            get {
                return this.IOEntryStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.IOEntryStatusField, value) != true)) {
                    this.IOEntryStatusField = value;
                    this.RaisePropertyChanged("IOEntryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReadPointer {
            get {
                return this.ReadPointerField;
            }
            set {
                if ((object.ReferenceEquals(this.ReadPointerField, value) != true)) {
                    this.ReadPointerField = value;
                    this.RaisePropertyChanged("ReadPointer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReaderID {
            get {
                return this.ReaderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReaderIDField, value) != true)) {
                    this.ReaderIDField = value;
                    this.RaisePropertyChanged("ReaderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReaderName {
            get {
                return this.ReaderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReaderNameField, value) != true)) {
                    this.ReaderNameField = value;
                    this.RaisePropertyChanged("ReaderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionCount {
            get {
                return this.TransactionCountField;
            }
            set {
                if ((this.TransactionCountField.Equals(value) != true)) {
                    this.TransactionCountField = value;
                    this.RaisePropertyChanged("TransactionCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aDateTime {
            get {
                return this.aDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.aDateTimeField, value) != true)) {
                    this.aDateTimeField = value;
                    this.RaisePropertyChanged("aDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISmartWebService")]
    public interface ISmartWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/ActivateCard", ReplyAction="http://tempuri.org/ISmartWebService/ActivateCardResponse")]
        EntityFrameworkDBF.ServiceReference1.CardStatus ActivateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/DeactivateCard", ReplyAction="http://tempuri.org/ISmartWebService/DeactivateCardResponse")]
        EntityFrameworkDBF.ServiceReference1.CardStatus DeactivateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/UpdateCard", ReplyAction="http://tempuri.org/ISmartWebService/UpdateCardResponse")]
        EntityFrameworkDBF.ServiceReference1.CardStatus UpdateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/DownLoadTemplate", ReplyAction="http://tempuri.org/ISmartWebService/DownLoadTemplateResponse")]
        EntityFrameworkDBF.ServiceReference1.TemplateStatus[] DownLoadTemplate(string CardNo, string ControllerNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/UploadTemplate", ReplyAction="http://tempuri.org/ISmartWebService/UploadTemplateResponse")]
        EntityFrameworkDBF.ServiceReference1.TemplateStatus[] UploadTemplate(string CardNo, string ControllerNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/CheckUploadedTemplateStatus", ReplyAction="http://tempuri.org/ISmartWebService/CheckUploadedTemplateStatusResponse")]
        EntityFrameworkDBF.ServiceReference1.TemplateStatus CheckUploadedTemplateStatus(string CardNo, string ControllerNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/CheckDownloadTemplateStatus", ReplyAction="http://tempuri.org/ISmartWebService/CheckDownloadTemplateStatusResponse")]
        EntityFrameworkDBF.ServiceReference1.TemplateStatus CheckDownloadTemplateStatus(string CardNo, string ControllerNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/GetCardHistory", ReplyAction="http://tempuri.org/ISmartWebService/GetCardHistoryResponse")]
        EntityFrameworkDBF.ServiceReference1.DeviceActivateCardClass[] GetCardHistory(string CardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/EnrollFinger", ReplyAction="http://tempuri.org/ISmartWebService/EnrollFingerResponse")]
        EntityFrameworkDBF.ServiceReference1.Enroll_Error_Code EnrollFinger(string CardNo, string ControllerNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartWebService/GetTransaction", ReplyAction="http://tempuri.org/ISmartWebService/GetTransactionResponse")]
        EntityFrameworkDBF.ServiceReference1.TransactionTable[] GetTransaction(int TrxPointer, int TrxCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartWebServiceChannel : EntityFrameworkDBF.ServiceReference1.ISmartWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartWebServiceClient : System.ServiceModel.ClientBase<EntityFrameworkDBF.ServiceReference1.ISmartWebService>, EntityFrameworkDBF.ServiceReference1.ISmartWebService {
        
        public SmartWebServiceClient() {
        }
        
        public SmartWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EntityFrameworkDBF.ServiceReference1.CardStatus ActivateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails) {
            return base.Channel.ActivateCard(cardDetails);
        }
        
        public EntityFrameworkDBF.ServiceReference1.CardStatus DeactivateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails) {
            return base.Channel.DeactivateCard(cardDetails);
        }
        
        public EntityFrameworkDBF.ServiceReference1.CardStatus UpdateCard(EntityFrameworkDBF.ServiceReference1.CardDetails cardDetails) {
            return base.Channel.UpdateCard(cardDetails);
        }
        
        public EntityFrameworkDBF.ServiceReference1.TemplateStatus[] DownLoadTemplate(string CardNo, string ControllerNo) {
            return base.Channel.DownLoadTemplate(CardNo, ControllerNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.TemplateStatus[] UploadTemplate(string CardNo, string ControllerNo) {
            return base.Channel.UploadTemplate(CardNo, ControllerNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.TemplateStatus CheckUploadedTemplateStatus(string CardNo, string ControllerNo) {
            return base.Channel.CheckUploadedTemplateStatus(CardNo, ControllerNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.TemplateStatus CheckDownloadTemplateStatus(string CardNo, string ControllerNo) {
            return base.Channel.CheckDownloadTemplateStatus(CardNo, ControllerNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.DeviceActivateCardClass[] GetCardHistory(string CardNo) {
            return base.Channel.GetCardHistory(CardNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.Enroll_Error_Code EnrollFinger(string CardNo, string ControllerNo) {
            return base.Channel.EnrollFinger(CardNo, ControllerNo);
        }
        
        public EntityFrameworkDBF.ServiceReference1.TransactionTable[] GetTransaction(int TrxPointer, int TrxCount) {
            return base.Channel.GetTransaction(TrxPointer, TrxCount);
        }
    }
}
