<%@ Page Title="" Language="C#" MasterPageFile="~/VMSMaster.master" AutoEventWireup="true"
    CodeBehind="COUNTRY.aspx.cs" Inherits="EntityFrameworkDBF.ADMIN_PANEL.COUNTY"
    Theme="Admin_Basic" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <script src="../Scripts/jquery-1.4.1.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.txtView').keyup(function () {
                $(this).val($(this).val().toUpperCase());
            });
        });
    </script>
    <style type="text/css">
        .uppercase
        {
            text-transform: uppercase;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
    <center>
        <div class="header_02">
            DVSC : PASS MANAGEMENT SYSTEM - <span id="spnDate" runat="server"></span>
            <br />
            <br />
            COUNTRY MASTER
        </div>
        <div style="padding-left: 600px">
            <asp:Button ID="btnhome" runat="server" Text="BACK TO HOME" CssClass="btnView" OnClick="btnhome_Click" />
            <asp:Button ID="btnpnlhome" runat="server" Text="BACK TO ADMIN PANEL" CssClass="btnView"
                OnClick="btnpnlhome_Click" />
        </div>
    </center>
    <center>
        <table>
            <tr>
                <td>
                    <asp:Label ID="lblcountry" runat="server" Text="COUNTRY" Style="font-size: x-large;"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtCountry" runat="server" CssClass="txtView" Placeholder="Enter Country"
                        Style="height: 25px"></asp:TextBox>
                </td>
                <td>
                    <asp:Label ID="lblnationality" runat="server" Text="NATIONALITY" Style="font-size: x-large;"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtNationality" runat="server" CssClass="txtView" Placeholder="Enter Nationality"
                        Style="height: 25px"></asp:TextBox>
                </td>
                <td>
                </td>
                <td>
                    <div class="btnView">
                        <asp:Button ID="btnSave" runat="server" Text="SAVE" OnClick="btnSave_Click" />
                    </div>
                </td>
            </tr>
        </table>
        <div class="btnView" style="padding-left: 900px">
            <asp:Button ID="btnGetRecord" runat="server" Text="GET DELETED RECORDS" OnClick="btnGetRecord_Click" />
        </div>
    </center>
    <center>
        <table>
            <tr>
                <td>
                    <div>
                        <asp:GridView ID="Gv_CountryMaster" runat="server" AutoGenerateColumns="false" AllowPaging="true"
                            SkinID="grid1" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px"
                            AlternatingRowStyle-BackColor="#ffffdd" CellPadding="3" OnPageIndexChanging="Gv_CountryMaster_PageIndexChanging"
                            OnRowCancelingEdit="Gv_CountryMaster_RowCancelingEdit" OnRowDeleting="Gv_CountryMaster_RowDeleting"
                            OnRowEditing="Gv_CountryMaster_RowEditing" OnRowUpdating="Gv_CountryMaster_RowUpdating"
                            AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" DataKeyNames="COUNTRY_ID">
                            <Columns>
                                <asp:TemplateField HeaderText="SL">
                                    <ItemTemplate>
                                        <%# Container.DataItemIndex + 1 %>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="COUNTRY NAME">
                                    <ItemTemplate>
                                        <asp:Label ID="lblCountryname" runat="server" Text='<%#Eval("COUNTRY_NAME") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtcountryname" runat="server" Text='<%#Eval("COUNTRY_NAME") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="NATIONALITY">
                                    <ItemTemplate>
                                        <asp:Label ID="lblNation" runat="server" Text='<%#Eval("NATIONALITY") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtNation" runat="server" Text='<%#Eval("NATIONALITY") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="DELETE FLAG">
                                    <ItemTemplate>
                                        <asp:Label ID="lblFlag" runat="server" Text='<%#Eval("FLAG") %>'></asp:Label>
                                        <asp:HiddenField runat="server" ID="hdn_Flag" Value='<%#Eval("FLAG") %>' />
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtFlag" runat="server" Text='<%#Eval("FLAG") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <%--<FooterStyle BackColor="White" ForeColor="#000066" />
                            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" CssClass="Pager" />
                            <RowStyle ForeColor="#000066" />
                            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#007DBB" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#00547E" />--%>
                        </asp:GridView>
                        <asp:HiddenField runat="server" ID="hdn_Flag_New" />
                    </div>
                </td>
            </tr>
        </table>
    </center>
</asp:Content>
