<%@ Page Title="" Language="C#" MasterPageFile="~/VMSMaster.master" AutoEventWireup="true"
    CodeBehind="SHOP.aspx.cs" Inherits="EntityFrameworkDBF.ADMIN_PANEL.SHOP" Theme="Admin_Basic" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <script src="../Scripts/jquery-1.4.1.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.txtView').keyup(function () {
                $(this).val($(this).val().toUpperCase());
            });
        });
    </script>
    <style type="text/css">
        .uppercase
        {
            text-transform: uppercase;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
    <center>
        <div class="header_02">
            DVSC : PASS MANAGEMENT SYSTEM - <span id="spnDate" runat="server"></span>
            <br />
            <br />
            SHIP MASTER
        </div>
        <div style="padding-left: 600px">
            <asp:Button ID="btnhome" runat="server" Text="BACK TO HOME" CssClass="btnView" OnClick="btnhome_Click" />
            <asp:Button ID="btnpnlhome" runat="server" Text="BACK TO ADMIN PANEL" CssClass="btnView"
                OnClick="btnpnlhome_Click" />
        </div>
    </center>
    <br />
    <center>
        <table>
            <tr>
                <td>
                    <asp:Label ID="lblShop" runat="server" Text="SHIP NAME " Style="font-size: x-large;"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtShop" runat="server" CssClass="txtView" Placeholder="Enter Shop"
                        Style="height: 25px"></asp:TextBox>
                </td>
                <td>
                </td>
                <td>
                    <div class="btnView">
                        <asp:Button ID="btnSave" runat="server" Text="SAVE" OnClick="btnSave_Click" />
                    </div>
                </td>
            </tr>
        </table>
        <br />
        <div class="btnView" style="padding-left: 900px">
            <asp:Button ID="btnGetRecord" runat="server" Text="GET DELETED RECORDS" OnClick="btnGetRecord_Click" />
        </div>
    </center>
    <br />
    <center>
        <table>
            <tr>
                <td>
                    <div>
                        <asp:GridView ID="Gv_ShopMaster" runat="server" AutoGenerateColumns="false" AllowPaging="true"
                            SkinID="grid1" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px"
                            AlternatingRowStyle-BackColor="#ffffdd" CellPadding="3" OnPageIndexChanging="Gv_ShopMaster_PageIndexChanging"
                            OnRowCancelingEdit="Gv_ShopMaster_RowCancelingEdit" OnRowDeleting="Gv_ShopMaster_RowDeleting"
                            OnRowEditing="Gv_ShopMaster_RowEditing" OnRowUpdating="Gv_ShopMaster_RowUpdating"
                            AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" DataKeyNames="SHOP_ID">
                            <Columns>
                                <asp:TemplateField HeaderText="SL">
                                    <ItemTemplate>
                                        <%# Container.DataItemIndex + 1 %>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="SHIP NAME">
                                    <ItemTemplate>
                                        <asp:Label ID="lblShopName" runat="server" Text='<%#Eval("SHOP_NAME") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtShopName" runat="server" Text='<%#Eval("SHOP_NAME") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="SHIP FILE NO">
                                    <ItemTemplate>
                                        <asp:Label ID="lblFileNo" runat="server" Text='<%#Eval("FILENO") %>'></asp:Label>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtFileNo" runat="server" Text='<%#Eval("FILENO") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="DELETE FLAG">
                                    <ItemTemplate>
                                        <asp:Label ID="lblFlag" runat="server" Text='<%#Eval("FLAG") %>'></asp:Label>
                                        <asp:HiddenField runat="server" ID="hdn_Flag" Value='<%#Eval("FLAG") %>' />
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtFlag" runat="server" Text='<%#Eval("FLAG") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <%--<FooterStyle BackColor="White" ForeColor="#000066" />
                            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" CssClass="Pager" />
                            <RowStyle ForeColor="#000066" />
                            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#007DBB" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#00547E" />--%>
                        </asp:GridView>
                        <asp:HiddenField runat="server" ID="hdn_Flag_New" />
                    </div>
                </td>
            </tr>
        </table>
    </center>
</asp:Content>
