//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EntityFrameworkDBF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DVSCEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DVSCEntities1 object using the connection string found in the 'DVSCEntities1' section of the application configuration file.
        /// </summary>
        public DVSCEntities1() : base("name=DVSCEntities1", "DVSCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DVSCEntities1 object.
        /// </summary>
        public DVSCEntities1(string connectionString) : base(connectionString, "DVSCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DVSCEntities1 object.
        /// </summary>
        public DVSCEntities1(EntityConnection connection) : base(connection, "DVSCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DESG_MASTER> DESG_MASTER
        {
            get
            {
                if ((_DESG_MASTER == null))
                {
                    _DESG_MASTER = base.CreateObjectSet<DESG_MASTER>("DESG_MASTER");
                }
                return _DESG_MASTER;
            }
        }
        private ObjectSet<DESG_MASTER> _DESG_MASTER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DESG_MASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDESG_MASTER(DESG_MASTER dESG_MASTER)
        {
            base.AddObject("DESG_MASTER", dESG_MASTER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DVSCModel", Name="DESG_MASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DESG_MASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DESG_MASTER object.
        /// </summary>
        /// <param name="dES_ID">Initial value of the DES_ID property.</param>
        /// <param name="dES_NAME">Initial value of the DES_NAME property.</param>
        public static DESG_MASTER CreateDESG_MASTER(global::System.Int32 dES_ID, global::System.String dES_NAME)
        {
            DESG_MASTER dESG_MASTER = new DESG_MASTER();
            dESG_MASTER.DES_ID = dES_ID;
            dESG_MASTER.DES_NAME = dES_NAME;
            return dESG_MASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DES_ID
        {
            get
            {
                return _DES_ID;
            }
            set
            {
                if (_DES_ID != value)
                {
                    OnDES_IDChanging(value);
                    ReportPropertyChanging("DES_ID");
                    _DES_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DES_ID");
                    OnDES_IDChanged();
                }
            }
        }
        private global::System.Int32 _DES_ID;
        partial void OnDES_IDChanging(global::System.Int32 value);
        partial void OnDES_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DES_NAME
        {
            get
            {
                return _DES_NAME;
            }
            set
            {
                OnDES_NAMEChanging(value);
                ReportPropertyChanging("DES_NAME");
                _DES_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DES_NAME");
                OnDES_NAMEChanged();
            }
        }
        private global::System.String _DES_NAME;
        partial void OnDES_NAMEChanging(global::System.String value);
        partial void OnDES_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DELETE_FLAG
        {
            get
            {
                return _DELETE_FLAG;
            }
            set
            {
                OnDELETE_FLAGChanging(value);
                ReportPropertyChanging("DELETE_FLAG");
                _DELETE_FLAG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DELETE_FLAG");
                OnDELETE_FLAGChanged();
            }
        }
        private global::System.String _DELETE_FLAG;
        partial void OnDELETE_FLAGChanging(global::System.String value);
        partial void OnDELETE_FLAGChanged();

        #endregion

    
    }

    #endregion

    
}
