//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SmartAccessModel", "FK_Transactions_Controllers", "Controller", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFrameworkDBF.Controller), "Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkDBF.Transaction), true)]

#endregion

namespace EntityFrameworkDBF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SmartAccessEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SmartAccessEntities object using the connection string found in the 'SmartAccessEntities' section of the application configuration file.
        /// </summary>
        public SmartAccessEntities() : base("name=SmartAccessEntities", "SmartAccessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SmartAccessEntities object.
        /// </summary>
        public SmartAccessEntities(string connectionString) : base(connectionString, "SmartAccessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SmartAccessEntities object.
        /// </summary>
        public SmartAccessEntities(EntityConnection connection) : base(connection, "SmartAccessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Controller> Controllers
        {
            get
            {
                if ((_Controllers == null))
                {
                    _Controllers = base.CreateObjectSet<Controller>("Controllers");
                }
                return _Controllers;
            }
        }
        private ObjectSet<Controller> _Controllers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DeviceTemplate> DeviceTemplates
        {
            get
            {
                if ((_DeviceTemplates == null))
                {
                    _DeviceTemplates = base.CreateObjectSet<DeviceTemplate>("DeviceTemplates");
                }
                return _DeviceTemplates;
            }
        }
        private ObjectSet<DeviceTemplate> _DeviceTemplates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction> Transactions
        {
            get
            {
                if ((_Transactions == null))
                {
                    _Transactions = base.CreateObjectSet<Transaction>("Transactions");
                }
                return _Transactions;
            }
        }
        private ObjectSet<Transaction> _Transactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Controllers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToControllers(Controller controller)
        {
            base.AddObject("Controllers", controller);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DeviceTemplates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeviceTemplates(DeviceTemplate deviceTemplate)
        {
            base.AddObject("DeviceTemplates", deviceTemplate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactions(Transaction transaction)
        {
            base.AddObject("Transactions", transaction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartAccessModel", Name="Controller")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Controller : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Controller object.
        /// </summary>
        /// <param name="controllerID">Initial value of the ControllerID property.</param>
        /// <param name="controllerNo">Initial value of the ControllerNo property.</param>
        /// <param name="controllerName">Initial value of the ControllerName property.</param>
        /// <param name="slaveID">Initial value of the SlaveID property.</param>
        /// <param name="companyLocationID">Initial value of the CompanyLocationID property.</param>
        /// <param name="controllerAuthenticationTypeID">Initial value of the ControllerAuthenticationTypeID property.</param>
        /// <param name="communicationTypeID">Initial value of the CommunicationTypeID property.</param>
        /// <param name="iPAddress">Initial value of the IPAddress property.</param>
        /// <param name="portNo">Initial value of the PortNo property.</param>
        /// <param name="noOfReaders">Initial value of the NoOfReaders property.</param>
        /// <param name="modelMasterID">Initial value of the ModelMasterID property.</param>
        /// <param name="serverIPStatus">Initial value of the ServerIPStatus property.</param>
        /// <param name="aPBStatus">Initial value of the APBStatus property.</param>
        /// <param name="mailStatus">Initial value of the MailStatus property.</param>
        /// <param name="netmask">Initial value of the Netmask property.</param>
        /// <param name="gateway">Initial value of the Gateway property.</param>
        /// <param name="controllerTypeID">Initial value of the ControllerTypeID property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="markDeleted">Initial value of the MarkDeleted property.</param>
        /// <param name="serialNo">Initial value of the SerialNo property.</param>
        /// <param name="devicePortNo">Initial value of the DevicePortNo property.</param>
        /// <param name="isMac">Initial value of the IsMac property.</param>
        /// <param name="isEnrolment">Initial value of the IsEnrolment property.</param>
        /// <param name="isTransactionDownload">Initial value of the IsTransactionDownload property.</param>
        /// <param name="pINStatus">Initial value of the PINStatus property.</param>
        /// <param name="facilityCode">Initial value of the FacilityCode property.</param>
        public static Controller CreateController(global::System.Int32 controllerID, global::System.Int32 controllerNo, global::System.String controllerName, global::System.Int32 slaveID, global::System.Int32 companyLocationID, global::System.Int32 controllerAuthenticationTypeID, global::System.Int32 communicationTypeID, global::System.String iPAddress, global::System.Int32 portNo, global::System.Int32 noOfReaders, global::System.Int32 modelMasterID, global::System.Boolean serverIPStatus, global::System.Boolean aPBStatus, global::System.Boolean mailStatus, global::System.String netmask, global::System.String gateway, global::System.Int32 controllerTypeID, global::System.DateTime createdDateTime, global::System.Boolean markDeleted, global::System.String serialNo, global::System.Int32 devicePortNo, global::System.Boolean isMac, global::System.Boolean isEnrolment, global::System.Boolean isTransactionDownload, global::System.Boolean pINStatus, global::System.Boolean facilityCode)
        {
            Controller controller = new Controller();
            controller.ControllerID = controllerID;
            controller.ControllerNo = controllerNo;
            controller.ControllerName = controllerName;
            controller.SlaveID = slaveID;
            controller.CompanyLocationID = companyLocationID;
            controller.ControllerAuthenticationTypeID = controllerAuthenticationTypeID;
            controller.CommunicationTypeID = communicationTypeID;
            controller.IPAddress = iPAddress;
            controller.PortNo = portNo;
            controller.NoOfReaders = noOfReaders;
            controller.ModelMasterID = modelMasterID;
            controller.ServerIPStatus = serverIPStatus;
            controller.APBStatus = aPBStatus;
            controller.MailStatus = mailStatus;
            controller.Netmask = netmask;
            controller.Gateway = gateway;
            controller.ControllerTypeID = controllerTypeID;
            controller.CreatedDateTime = createdDateTime;
            controller.MarkDeleted = markDeleted;
            controller.SerialNo = serialNo;
            controller.DevicePortNo = devicePortNo;
            controller.IsMac = isMac;
            controller.IsEnrolment = isEnrolment;
            controller.IsTransactionDownload = isTransactionDownload;
            controller.PINStatus = pINStatus;
            controller.FacilityCode = facilityCode;
            return controller;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerID
        {
            get
            {
                return _ControllerID;
            }
            set
            {
                if (_ControllerID != value)
                {
                    OnControllerIDChanging(value);
                    ReportPropertyChanging("ControllerID");
                    _ControllerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ControllerID");
                    OnControllerIDChanged();
                }
            }
        }
        private global::System.Int32 _ControllerID;
        partial void OnControllerIDChanging(global::System.Int32 value);
        partial void OnControllerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerNo
        {
            get
            {
                return _ControllerNo;
            }
            set
            {
                OnControllerNoChanging(value);
                ReportPropertyChanging("ControllerNo");
                _ControllerNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerNo");
                OnControllerNoChanged();
            }
        }
        private global::System.Int32 _ControllerNo;
        partial void OnControllerNoChanging(global::System.Int32 value);
        partial void OnControllerNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ControllerName
        {
            get
            {
                return _ControllerName;
            }
            set
            {
                OnControllerNameChanging(value);
                ReportPropertyChanging("ControllerName");
                _ControllerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ControllerName");
                OnControllerNameChanged();
            }
        }
        private global::System.String _ControllerName;
        partial void OnControllerNameChanging(global::System.String value);
        partial void OnControllerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SlaveID
        {
            get
            {
                return _SlaveID;
            }
            set
            {
                OnSlaveIDChanging(value);
                ReportPropertyChanging("SlaveID");
                _SlaveID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlaveID");
                OnSlaveIDChanged();
            }
        }
        private global::System.Int32 _SlaveID;
        partial void OnSlaveIDChanging(global::System.Int32 value);
        partial void OnSlaveIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyLocationID
        {
            get
            {
                return _CompanyLocationID;
            }
            set
            {
                OnCompanyLocationIDChanging(value);
                ReportPropertyChanging("CompanyLocationID");
                _CompanyLocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyLocationID");
                OnCompanyLocationIDChanged();
            }
        }
        private global::System.Int32 _CompanyLocationID;
        partial void OnCompanyLocationIDChanging(global::System.Int32 value);
        partial void OnCompanyLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerAuthenticationTypeID
        {
            get
            {
                return _ControllerAuthenticationTypeID;
            }
            set
            {
                OnControllerAuthenticationTypeIDChanging(value);
                ReportPropertyChanging("ControllerAuthenticationTypeID");
                _ControllerAuthenticationTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerAuthenticationTypeID");
                OnControllerAuthenticationTypeIDChanged();
            }
        }
        private global::System.Int32 _ControllerAuthenticationTypeID;
        partial void OnControllerAuthenticationTypeIDChanging(global::System.Int32 value);
        partial void OnControllerAuthenticationTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommunicationTypeID
        {
            get
            {
                return _CommunicationTypeID;
            }
            set
            {
                OnCommunicationTypeIDChanging(value);
                ReportPropertyChanging("CommunicationTypeID");
                _CommunicationTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommunicationTypeID");
                OnCommunicationTypeIDChanged();
            }
        }
        private global::System.Int32 _CommunicationTypeID;
        partial void OnCommunicationTypeIDChanging(global::System.Int32 value);
        partial void OnCommunicationTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPAddress
        {
            get
            {
                return _IPAddress;
            }
            set
            {
                OnIPAddressChanging(value);
                ReportPropertyChanging("IPAddress");
                _IPAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPAddress");
                OnIPAddressChanged();
            }
        }
        private global::System.String _IPAddress;
        partial void OnIPAddressChanging(global::System.String value);
        partial void OnIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PortNo
        {
            get
            {
                return _PortNo;
            }
            set
            {
                OnPortNoChanging(value);
                ReportPropertyChanging("PortNo");
                _PortNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortNo");
                OnPortNoChanged();
            }
        }
        private global::System.Int32 _PortNo;
        partial void OnPortNoChanging(global::System.Int32 value);
        partial void OnPortNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoOfReaders
        {
            get
            {
                return _NoOfReaders;
            }
            set
            {
                OnNoOfReadersChanging(value);
                ReportPropertyChanging("NoOfReaders");
                _NoOfReaders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoOfReaders");
                OnNoOfReadersChanged();
            }
        }
        private global::System.Int32 _NoOfReaders;
        partial void OnNoOfReadersChanging(global::System.Int32 value);
        partial void OnNoOfReadersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResponseTimeMultiplier
        {
            get
            {
                return _ResponseTimeMultiplier;
            }
            set
            {
                OnResponseTimeMultiplierChanging(value);
                ReportPropertyChanging("ResponseTimeMultiplier");
                _ResponseTimeMultiplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResponseTimeMultiplier");
                OnResponseTimeMultiplierChanged();
            }
        }
        private global::System.String _ResponseTimeMultiplier;
        partial void OnResponseTimeMultiplierChanging(global::System.String value);
        partial void OnResponseTimeMultiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelMasterID
        {
            get
            {
                return _ModelMasterID;
            }
            set
            {
                OnModelMasterIDChanging(value);
                ReportPropertyChanging("ModelMasterID");
                _ModelMasterID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelMasterID");
                OnModelMasterIDChanged();
            }
        }
        private global::System.Int32 _ModelMasterID;
        partial void OnModelMasterIDChanging(global::System.Int32 value);
        partial void OnModelMasterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SwipeFrequencyTime
        {
            get
            {
                return _SwipeFrequencyTime;
            }
            set
            {
                OnSwipeFrequencyTimeChanging(value);
                ReportPropertyChanging("SwipeFrequencyTime");
                _SwipeFrequencyTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SwipeFrequencyTime");
                OnSwipeFrequencyTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _SwipeFrequencyTime;
        partial void OnSwipeFrequencyTimeChanging(Nullable<global::System.Int32> value);
        partial void OnSwipeFrequencyTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServerIP
        {
            get
            {
                return _ServerIP;
            }
            set
            {
                OnServerIPChanging(value);
                ReportPropertyChanging("ServerIP");
                _ServerIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServerIP");
                OnServerIPChanged();
            }
        }
        private global::System.String _ServerIP;
        partial void OnServerIPChanging(global::System.String value);
        partial void OnServerIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ServerIPStatus
        {
            get
            {
                return _ServerIPStatus;
            }
            set
            {
                OnServerIPStatusChanging(value);
                ReportPropertyChanging("ServerIPStatus");
                _ServerIPStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServerIPStatus");
                OnServerIPStatusChanged();
            }
        }
        private global::System.Boolean _ServerIPStatus;
        partial void OnServerIPStatusChanging(global::System.Boolean value);
        partial void OnServerIPStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean APBStatus
        {
            get
            {
                return _APBStatus;
            }
            set
            {
                OnAPBStatusChanging(value);
                ReportPropertyChanging("APBStatus");
                _APBStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APBStatus");
                OnAPBStatusChanged();
            }
        }
        private global::System.Boolean _APBStatus;
        partial void OnAPBStatusChanging(global::System.Boolean value);
        partial void OnAPBStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APBType
        {
            get
            {
                return _APBType;
            }
            set
            {
                OnAPBTypeChanging(value);
                ReportPropertyChanging("APBType");
                _APBType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APBType");
                OnAPBTypeChanged();
            }
        }
        private global::System.String _APBType;
        partial void OnAPBTypeChanging(global::System.String value);
        partial void OnAPBTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DNS
        {
            get
            {
                return _DNS;
            }
            set
            {
                OnDNSChanging(value);
                ReportPropertyChanging("DNS");
                _DNS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DNS");
                OnDNSChanged();
            }
        }
        private global::System.String _DNS;
        partial void OnDNSChanging(global::System.String value);
        partial void OnDNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailServerName
        {
            get
            {
                return _MailServerName;
            }
            set
            {
                OnMailServerNameChanging(value);
                ReportPropertyChanging("MailServerName");
                _MailServerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MailServerName");
                OnMailServerNameChanged();
            }
        }
        private global::System.String _MailServerName;
        partial void OnMailServerNameChanging(global::System.String value);
        partial void OnMailServerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AuthEmailID
        {
            get
            {
                return _AuthEmailID;
            }
            set
            {
                OnAuthEmailIDChanging(value);
                ReportPropertyChanging("AuthEmailID");
                _AuthEmailID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AuthEmailID");
                OnAuthEmailIDChanged();
            }
        }
        private global::System.String _AuthEmailID;
        partial void OnAuthEmailIDChanging(global::System.String value);
        partial void OnAuthEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailPassword
        {
            get
            {
                return _EmailPassword;
            }
            set
            {
                OnEmailPasswordChanging(value);
                ReportPropertyChanging("EmailPassword");
                _EmailPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailPassword");
                OnEmailPasswordChanged();
            }
        }
        private global::System.String _EmailPassword;
        partial void OnEmailPasswordChanging(global::System.String value);
        partial void OnEmailPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MailStatus
        {
            get
            {
                return _MailStatus;
            }
            set
            {
                OnMailStatusChanging(value);
                ReportPropertyChanging("MailStatus");
                _MailStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MailStatus");
                OnMailStatusChanged();
            }
        }
        private global::System.Boolean _MailStatus;
        partial void OnMailStatusChanging(global::System.Boolean value);
        partial void OnMailStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReaderCombination
        {
            get
            {
                return _ReaderCombination;
            }
            set
            {
                OnReaderCombinationChanging(value);
                ReportPropertyChanging("ReaderCombination");
                _ReaderCombination = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReaderCombination");
                OnReaderCombinationChanged();
            }
        }
        private global::System.String _ReaderCombination;
        partial void OnReaderCombinationChanging(global::System.String value);
        partial void OnReaderCombinationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Netmask
        {
            get
            {
                return _Netmask;
            }
            set
            {
                OnNetmaskChanging(value);
                ReportPropertyChanging("Netmask");
                _Netmask = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Netmask");
                OnNetmaskChanged();
            }
        }
        private global::System.String _Netmask;
        partial void OnNetmaskChanging(global::System.String value);
        partial void OnNetmaskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gateway
        {
            get
            {
                return _Gateway;
            }
            set
            {
                OnGatewayChanging(value);
                ReportPropertyChanging("Gateway");
                _Gateway = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gateway");
                OnGatewayChanged();
            }
        }
        private global::System.String _Gateway;
        partial void OnGatewayChanging(global::System.String value);
        partial void OnGatewayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerTypeID
        {
            get
            {
                return _ControllerTypeID;
            }
            set
            {
                OnControllerTypeIDChanging(value);
                ReportPropertyChanging("ControllerTypeID");
                _ControllerTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerTypeID");
                OnControllerTypeIDChanged();
            }
        }
        private global::System.Int32 _ControllerTypeID;
        partial void OnControllerTypeIDChanging(global::System.Int32 value);
        partial void OnControllerTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MarkDeleted
        {
            get
            {
                return _MarkDeleted;
            }
            set
            {
                OnMarkDeletedChanging(value);
                ReportPropertyChanging("MarkDeleted");
                _MarkDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarkDeleted");
                OnMarkDeletedChanged();
            }
        }
        private global::System.Boolean _MarkDeleted;
        partial void OnMarkDeletedChanging(global::System.Boolean value);
        partial void OnMarkDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultGateway
        {
            get
            {
                return _DefaultGateway;
            }
            set
            {
                OnDefaultGatewayChanging(value);
                ReportPropertyChanging("DefaultGateway");
                _DefaultGateway = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultGateway");
                OnDefaultGatewayChanged();
            }
        }
        private global::System.String _DefaultGateway;
        partial void OnDefaultGatewayChanging(global::System.String value);
        partial void OnDefaultGatewayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNo
        {
            get
            {
                return _SerialNo;
            }
            set
            {
                OnSerialNoChanging(value);
                ReportPropertyChanging("SerialNo");
                _SerialNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SerialNo");
                OnSerialNoChanged();
            }
        }
        private global::System.String _SerialNo;
        partial void OnSerialNoChanging(global::System.String value);
        partial void OnSerialNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MACAddress
        {
            get
            {
                return _MACAddress;
            }
            set
            {
                OnMACAddressChanging(value);
                ReportPropertyChanging("MACAddress");
                _MACAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MACAddress");
                OnMACAddressChanged();
            }
        }
        private global::System.String _MACAddress;
        partial void OnMACAddressChanging(global::System.String value);
        partial void OnMACAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeviceIP
        {
            get
            {
                return _DeviceIP;
            }
            set
            {
                OnDeviceIPChanging(value);
                ReportPropertyChanging("DeviceIP");
                _DeviceIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeviceIP");
                OnDeviceIPChanged();
            }
        }
        private global::System.String _DeviceIP;
        partial void OnDeviceIPChanging(global::System.String value);
        partial void OnDeviceIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DevicePortNo
        {
            get
            {
                return _DevicePortNo;
            }
            set
            {
                OnDevicePortNoChanging(value);
                ReportPropertyChanging("DevicePortNo");
                _DevicePortNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevicePortNo");
                OnDevicePortNoChanged();
            }
        }
        private global::System.Int32 _DevicePortNo;
        partial void OnDevicePortNoChanging(global::System.Int32 value);
        partial void OnDevicePortNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMac
        {
            get
            {
                return _IsMac;
            }
            set
            {
                OnIsMacChanging(value);
                ReportPropertyChanging("IsMac");
                _IsMac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMac");
                OnIsMacChanged();
            }
        }
        private global::System.Boolean _IsMac;
        partial void OnIsMacChanging(global::System.Boolean value);
        partial void OnIsMacChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnrolment
        {
            get
            {
                return _IsEnrolment;
            }
            set
            {
                OnIsEnrolmentChanging(value);
                ReportPropertyChanging("IsEnrolment");
                _IsEnrolment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnrolment");
                OnIsEnrolmentChanged();
            }
        }
        private global::System.Boolean _IsEnrolment;
        partial void OnIsEnrolmentChanging(global::System.Boolean value);
        partial void OnIsEnrolmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModelTypeID
        {
            get
            {
                return _ModelTypeID;
            }
            set
            {
                OnModelTypeIDChanging(value);
                ReportPropertyChanging("ModelTypeID");
                _ModelTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelTypeID");
                OnModelTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModelTypeID;
        partial void OnModelTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnModelTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BioEnrollType
        {
            get
            {
                return _BioEnrollType;
            }
            set
            {
                OnBioEnrollTypeChanging(value);
                ReportPropertyChanging("BioEnrollType");
                _BioEnrollType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BioEnrollType");
                OnBioEnrollTypeChanged();
            }
        }
        private global::System.String _BioEnrollType;
        partial void OnBioEnrollTypeChanging(global::System.String value);
        partial void OnBioEnrollTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ControllerCommunicationTypeID
        {
            get
            {
                return _ControllerCommunicationTypeID;
            }
            set
            {
                OnControllerCommunicationTypeIDChanging(value);
                ReportPropertyChanging("ControllerCommunicationTypeID");
                _ControllerCommunicationTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerCommunicationTypeID");
                OnControllerCommunicationTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ControllerCommunicationTypeID;
        partial void OnControllerCommunicationTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnControllerCommunicationTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DynaDNS
        {
            get
            {
                return _DynaDNS;
            }
            set
            {
                OnDynaDNSChanging(value);
                ReportPropertyChanging("DynaDNS");
                _DynaDNS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DynaDNS");
                OnDynaDNSChanged();
            }
        }
        private global::System.String _DynaDNS;
        partial void OnDynaDNSChanging(global::System.String value);
        partial void OnDynaDNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResetAPBStatus
        {
            get
            {
                return _ResetAPBStatus;
            }
            set
            {
                OnResetAPBStatusChanging(value);
                ReportPropertyChanging("ResetAPBStatus");
                _ResetAPBStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResetAPBStatus");
                OnResetAPBStatusChanged();
            }
        }
        private global::System.String _ResetAPBStatus;
        partial void OnResetAPBStatusChanging(global::System.String value);
        partial void OnResetAPBStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessStr
        {
            get
            {
                return _ProcessStr;
            }
            set
            {
                OnProcessStrChanging(value);
                ReportPropertyChanging("ProcessStr");
                _ProcessStr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessStr");
                OnProcessStrChanged();
            }
        }
        private global::System.String _ProcessStr;
        partial void OnProcessStrChanging(global::System.String value);
        partial void OnProcessStrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdateTime
        {
            get
            {
                return _LastUpdateTime;
            }
            set
            {
                OnLastUpdateTimeChanging(value);
                ReportPropertyChanging("LastUpdateTime");
                _LastUpdateTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdateTime");
                OnLastUpdateTimeChanged();
            }
        }
        private global::System.String _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(global::System.String value);
        partial void OnLastUpdateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remote_Host
        {
            get
            {
                return _Remote_Host;
            }
            set
            {
                OnRemote_HostChanging(value);
                ReportPropertyChanging("Remote_Host");
                _Remote_Host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remote_Host");
                OnRemote_HostChanged();
            }
        }
        private global::System.String _Remote_Host;
        partial void OnRemote_HostChanging(global::System.String value);
        partial void OnRemote_HostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsTransactionDownload
        {
            get
            {
                return _IsTransactionDownload;
            }
            set
            {
                OnIsTransactionDownloadChanging(value);
                ReportPropertyChanging("IsTransactionDownload");
                _IsTransactionDownload = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTransactionDownload");
                OnIsTransactionDownloadChanged();
            }
        }
        private global::System.Boolean _IsTransactionDownload;
        partial void OnIsTransactionDownloadChanging(global::System.Boolean value);
        partial void OnIsTransactionDownloadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PINStatus
        {
            get
            {
                return _PINStatus;
            }
            set
            {
                OnPINStatusChanging(value);
                ReportPropertyChanging("PINStatus");
                _PINStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PINStatus");
                OnPINStatusChanged();
            }
        }
        private global::System.Boolean _PINStatus;
        partial void OnPINStatusChanging(global::System.Boolean value);
        partial void OnPINStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FacilityCode
        {
            get
            {
                return _FacilityCode;
            }
            set
            {
                OnFacilityCodeChanging(value);
                ReportPropertyChanging("FacilityCode");
                _FacilityCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacilityCode");
                OnFacilityCodeChanged();
            }
        }
        private global::System.Boolean _FacilityCode;
        partial void OnFacilityCodeChanging(global::System.Boolean value);
        partial void OnFacilityCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastTrn_TM
        {
            get
            {
                return _LastTrn_TM;
            }
            set
            {
                OnLastTrn_TMChanging(value);
                ReportPropertyChanging("LastTrn_TM");
                _LastTrn_TM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastTrn_TM");
                OnLastTrn_TMChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastTrn_TM;
        partial void OnLastTrn_TMChanging(Nullable<global::System.DateTime> value);
        partial void OnLastTrn_TMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastHB_TM
        {
            get
            {
                return _LastHB_TM;
            }
            set
            {
                OnLastHB_TMChanging(value);
                ReportPropertyChanging("LastHB_TM");
                _LastHB_TM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastHB_TM");
                OnLastHB_TMChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastHB_TM;
        partial void OnLastHB_TMChanging(Nullable<global::System.DateTime> value);
        partial void OnLastHB_TMChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartAccessModel", "FK_Transactions_Controllers", "Transaction")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("SmartAccessModel.FK_Transactions_Controllers", "Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("SmartAccessModel.FK_Transactions_Controllers", "Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartAccessModel", Name="DeviceTemplate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeviceTemplate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DeviceTemplate object.
        /// </summary>
        /// <param name="deviceTemplateID">Initial value of the DeviceTemplateID property.</param>
        /// <param name="cardNo">Initial value of the CardNo property.</param>
        /// <param name="controllerID">Initial value of the ControllerID property.</param>
        /// <param name="updateTime">Initial value of the UpdateTime property.</param>
        /// <param name="synchTime">Initial value of the SynchTime property.</param>
        /// <param name="tryCount">Initial value of the TryCount property.</param>
        public static DeviceTemplate CreateDeviceTemplate(global::System.Int32 deviceTemplateID, global::System.String cardNo, global::System.Int32 controllerID, global::System.DateTime updateTime, global::System.DateTime synchTime, global::System.Int32 tryCount)
        {
            DeviceTemplate deviceTemplate = new DeviceTemplate();
            deviceTemplate.DeviceTemplateID = deviceTemplateID;
            deviceTemplate.CardNo = cardNo;
            deviceTemplate.ControllerID = controllerID;
            deviceTemplate.UpdateTime = updateTime;
            deviceTemplate.SynchTime = synchTime;
            deviceTemplate.TryCount = tryCount;
            return deviceTemplate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceTemplateID
        {
            get
            {
                return _DeviceTemplateID;
            }
            set
            {
                if (_DeviceTemplateID != value)
                {
                    OnDeviceTemplateIDChanging(value);
                    ReportPropertyChanging("DeviceTemplateID");
                    _DeviceTemplateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceTemplateID");
                    OnDeviceTemplateIDChanged();
                }
            }
        }
        private global::System.Int32 _DeviceTemplateID;
        partial void OnDeviceTemplateIDChanging(global::System.Int32 value);
        partial void OnDeviceTemplateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeID;
        partial void OnEmployeeIDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardNo
        {
            get
            {
                return _CardNo;
            }
            set
            {
                OnCardNoChanging(value);
                ReportPropertyChanging("CardNo");
                _CardNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardNo");
                OnCardNoChanged();
            }
        }
        private global::System.String _CardNo;
        partial void OnCardNoChanging(global::System.String value);
        partial void OnCardNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateNo
        {
            get
            {
                return _TemplateNo;
            }
            set
            {
                OnTemplateNoChanging(value);
                ReportPropertyChanging("TemplateNo");
                _TemplateNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateNo");
                OnTemplateNoChanged();
            }
        }
        private global::System.String _TemplateNo;
        partial void OnTemplateNoChanging(global::System.String value);
        partial void OnTemplateNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateData
        {
            get
            {
                return _TemplateData;
            }
            set
            {
                OnTemplateDataChanging(value);
                ReportPropertyChanging("TemplateData");
                _TemplateData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateData");
                OnTemplateDataChanged();
            }
        }
        private global::System.String _TemplateData;
        partial void OnTemplateDataChanging(global::System.String value);
        partial void OnTemplateDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateSize
        {
            get
            {
                return _TemplateSize;
            }
            set
            {
                OnTemplateSizeChanging(value);
                ReportPropertyChanging("TemplateSize");
                _TemplateSize = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateSize");
                OnTemplateSizeChanged();
            }
        }
        private global::System.String _TemplateSize;
        partial void OnTemplateSizeChanging(global::System.String value);
        partial void OnTemplateSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerID
        {
            get
            {
                return _ControllerID;
            }
            set
            {
                OnControllerIDChanging(value);
                ReportPropertyChanging("ControllerID");
                _ControllerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerID");
                OnControllerIDChanged();
            }
        }
        private global::System.Int32 _ControllerID;
        partial void OnControllerIDChanging(global::System.Int32 value);
        partial void OnControllerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private global::System.DateTime _UpdateTime;
        partial void OnUpdateTimeChanging(global::System.DateTime value);
        partial void OnUpdateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SynchTime
        {
            get
            {
                return _SynchTime;
            }
            set
            {
                OnSynchTimeChanging(value);
                ReportPropertyChanging("SynchTime");
                _SynchTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SynchTime");
                OnSynchTimeChanged();
            }
        }
        private global::System.DateTime _SynchTime;
        partial void OnSynchTimeChanging(global::System.DateTime value);
        partial void OnSynchTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateSource
        {
            get
            {
                return _TemplateSource;
            }
            set
            {
                OnTemplateSourceChanging(value);
                ReportPropertyChanging("TemplateSource");
                _TemplateSource = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateSource");
                OnTemplateSourceChanged();
            }
        }
        private global::System.String _TemplateSource;
        partial void OnTemplateSourceChanging(global::System.String value);
        partial void OnTemplateSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SynchStatus
        {
            get
            {
                return _SynchStatus;
            }
            set
            {
                OnSynchStatusChanging(value);
                ReportPropertyChanging("SynchStatus");
                _SynchStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SynchStatus");
                OnSynchStatusChanged();
            }
        }
        private global::System.String _SynchStatus;
        partial void OnSynchStatusChanging(global::System.String value);
        partial void OnSynchStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemplateType
        {
            get
            {
                return _TemplateType;
            }
            set
            {
                OnTemplateTypeChanging(value);
                ReportPropertyChanging("TemplateType");
                _TemplateType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemplateType");
                OnTemplateTypeChanged();
            }
        }
        private global::System.String _TemplateType;
        partial void OnTemplateTypeChanging(global::System.String value);
        partial void OnTemplateTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TryCount
        {
            get
            {
                return _TryCount;
            }
            set
            {
                OnTryCountChanging(value);
                ReportPropertyChanging("TryCount");
                _TryCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TryCount");
                OnTryCountChanged();
            }
        }
        private global::System.Int32 _TryCount;
        partial void OnTryCountChanging(global::System.Int32 value);
        partial void OnTryCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MarkDeleted
        {
            get
            {
                return _MarkDeleted;
            }
            set
            {
                OnMarkDeletedChanging(value);
                ReportPropertyChanging("MarkDeleted");
                _MarkDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarkDeleted");
                OnMarkDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _MarkDeleted;
        partial void OnMarkDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnMarkDeletedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartAccessModel", Name="Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="transactionID">Initial value of the TransactionID property.</param>
        /// <param name="controllerID">Initial value of the ControllerID property.</param>
        /// <param name="cardNo">Initial value of the CardNo property.</param>
        /// <param name="eventCode">Initial value of the EventCode property.</param>
        /// <param name="aDateTime">Initial value of the aDateTime property.</param>
        /// <param name="facilityCode">Initial value of the FacilityCode property.</param>
        public static Transaction CreateTransaction(global::System.Int32 transactionID, global::System.Int32 controllerID, global::System.String cardNo, global::System.Int32 eventCode, global::System.DateTime aDateTime, global::System.Int32 facilityCode)
        {
            Transaction transaction = new Transaction();
            transaction.TransactionID = transactionID;
            transaction.ControllerID = controllerID;
            transaction.CardNo = cardNo;
            transaction.EventCode = eventCode;
            transaction.aDateTime = aDateTime;
            transaction.FacilityCode = facilityCode;
            return transaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                if (_TransactionID != value)
                {
                    OnTransactionIDChanging(value);
                    ReportPropertyChanging("TransactionID");
                    _TransactionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransactionID");
                    OnTransactionIDChanged();
                }
            }
        }
        private global::System.Int32 _TransactionID;
        partial void OnTransactionIDChanging(global::System.Int32 value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ControllerID
        {
            get
            {
                return _ControllerID;
            }
            set
            {
                OnControllerIDChanging(value);
                ReportPropertyChanging("ControllerID");
                _ControllerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerID");
                OnControllerIDChanged();
            }
        }
        private global::System.Int32 _ControllerID;
        partial void OnControllerIDChanging(global::System.Int32 value);
        partial void OnControllerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardNo
        {
            get
            {
                return _CardNo;
            }
            set
            {
                OnCardNoChanging(value);
                ReportPropertyChanging("CardNo");
                _CardNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardNo");
                OnCardNoChanged();
            }
        }
        private global::System.String _CardNo;
        partial void OnCardNoChanging(global::System.String value);
        partial void OnCardNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSNNo
        {
            get
            {
                return _CSNNo;
            }
            set
            {
                OnCSNNoChanging(value);
                ReportPropertyChanging("CSNNo");
                _CSNNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSNNo");
                OnCSNNoChanged();
            }
        }
        private global::System.String _CSNNo;
        partial void OnCSNNoChanging(global::System.String value);
        partial void OnCSNNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeFunctionCardID
        {
            get
            {
                return _EmployeeFunctionCardID;
            }
            set
            {
                OnEmployeeFunctionCardIDChanging(value);
                ReportPropertyChanging("EmployeeFunctionCardID");
                _EmployeeFunctionCardID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeFunctionCardID");
                OnEmployeeFunctionCardIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeFunctionCardID;
        partial void OnEmployeeFunctionCardIDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeFunctionCardIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReaderID
        {
            get
            {
                return _ReaderID;
            }
            set
            {
                OnReaderIDChanging(value);
                ReportPropertyChanging("ReaderID");
                _ReaderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReaderID");
                OnReaderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ReaderID;
        partial void OnReaderIDChanging(Nullable<global::System.Int32> value);
        partial void OnReaderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventCode
        {
            get
            {
                return _EventCode;
            }
            set
            {
                OnEventCodeChanging(value);
                ReportPropertyChanging("EventCode");
                _EventCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventCode");
                OnEventCodeChanged();
            }
        }
        private global::System.Int32 _EventCode;
        partial void OnEventCodeChanging(global::System.Int32 value);
        partial void OnEventCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime aDateTime
        {
            get
            {
                return _aDateTime;
            }
            set
            {
                OnaDateTimeChanging(value);
                ReportPropertyChanging("aDateTime");
                _aDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aDateTime");
                OnaDateTimeChanged();
            }
        }
        private global::System.DateTime _aDateTime;
        partial void OnaDateTimeChanging(global::System.DateTime value);
        partial void OnaDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TransactionCount
        {
            get
            {
                return _TransactionCount;
            }
            set
            {
                OnTransactionCountChanging(value);
                ReportPropertyChanging("TransactionCount");
                _TransactionCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransactionCount");
                OnTransactionCountChanged();
            }
        }
        private Nullable<global::System.Int32> _TransactionCount;
        partial void OnTransactionCountChanging(Nullable<global::System.Int32> value);
        partial void OnTransactionCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReadPointer
        {
            get
            {
                return _ReadPointer;
            }
            set
            {
                OnReadPointerChanging(value);
                ReportPropertyChanging("ReadPointer");
                _ReadPointer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadPointer");
                OnReadPointerChanged();
            }
        }
        private Nullable<global::System.Int32> _ReadPointer;
        partial void OnReadPointerChanging(Nullable<global::System.Int32> value);
        partial void OnReadPointerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityCode
        {
            get
            {
                return _FacilityCode;
            }
            set
            {
                OnFacilityCodeChanging(value);
                ReportPropertyChanging("FacilityCode");
                _FacilityCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacilityCode");
                OnFacilityCodeChanged();
            }
        }
        private global::System.Int32 _FacilityCode;
        partial void OnFacilityCodeChanging(global::System.Int32 value);
        partial void OnFacilityCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PCIPAddress
        {
            get
            {
                return _PCIPAddress;
            }
            set
            {
                OnPCIPAddressChanging(value);
                ReportPropertyChanging("PCIPAddress");
                _PCIPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PCIPAddress");
                OnPCIPAddressChanged();
            }
        }
        private global::System.String _PCIPAddress;
        partial void OnPCIPAddressChanging(global::System.String value);
        partial void OnPCIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventMessageName
        {
            get
            {
                return _EventMessageName;
            }
            set
            {
                OnEventMessageNameChanging(value);
                ReportPropertyChanging("EventMessageName");
                _EventMessageName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventMessageName");
                OnEventMessageNameChanged();
            }
        }
        private global::System.String _EventMessageName;
        partial void OnEventMessageNameChanging(global::System.String value);
        partial void OnEventMessageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TranSendsServiceID
        {
            get
            {
                return _TranSendsServiceID;
            }
            set
            {
                OnTranSendsServiceIDChanging(value);
                ReportPropertyChanging("TranSendsServiceID");
                _TranSendsServiceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TranSendsServiceID");
                OnTranSendsServiceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TranSendsServiceID;
        partial void OnTranSendsServiceIDChanging(Nullable<global::System.Int32> value);
        partial void OnTranSendsServiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChannelNo
        {
            get
            {
                return _ChannelNo;
            }
            set
            {
                OnChannelNoChanging(value);
                ReportPropertyChanging("ChannelNo");
                _ChannelNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChannelNo");
                OnChannelNoChanged();
            }
        }
        private Nullable<global::System.Int32> _ChannelNo;
        partial void OnChannelNoChanging(Nullable<global::System.Int32> value);
        partial void OnChannelNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> INOUTDate
        {
            get
            {
                return _INOUTDate;
            }
            set
            {
                OnINOUTDateChanging(value);
                ReportPropertyChanging("INOUTDate");
                _INOUTDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INOUTDate");
                OnINOUTDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _INOUTDate;
        partial void OnINOUTDateChanging(Nullable<global::System.DateTime> value);
        partial void OnINOUTDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> INOUT
        {
            get
            {
                return _INOUT;
            }
            set
            {
                OnINOUTChanging(value);
                ReportPropertyChanging("INOUT");
                _INOUT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INOUT");
                OnINOUTChanged();
            }
        }
        private Nullable<global::System.Byte> _INOUT;
        partial void OnINOUTChanging(Nullable<global::System.Byte> value);
        partial void OnINOUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IOCOUNT
        {
            get
            {
                return _IOCOUNT;
            }
            set
            {
                OnIOCOUNTChanging(value);
                ReportPropertyChanging("IOCOUNT");
                _IOCOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IOCOUNT");
                OnIOCOUNTChanged();
            }
        }
        private Nullable<global::System.Int16> _IOCOUNT;
        partial void OnIOCOUNTChanging(Nullable<global::System.Int16> value);
        partial void OnIOCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> INOUT_R2
        {
            get
            {
                return _INOUT_R2;
            }
            set
            {
                OnINOUT_R2Changing(value);
                ReportPropertyChanging("INOUT_R2");
                _INOUT_R2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INOUT_R2");
                OnINOUT_R2Changed();
            }
        }
        private Nullable<global::System.Byte> _INOUT_R2;
        partial void OnINOUT_R2Changing(Nullable<global::System.Byte> value);
        partial void OnINOUT_R2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IOCOUNT_R2
        {
            get
            {
                return _IOCOUNT_R2;
            }
            set
            {
                OnIOCOUNT_R2Changing(value);
                ReportPropertyChanging("IOCOUNT_R2");
                _IOCOUNT_R2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IOCOUNT_R2");
                OnIOCOUNT_R2Changed();
            }
        }
        private Nullable<global::System.Int16> _IOCOUNT_R2;
        partial void OnIOCOUNT_R2Changing(Nullable<global::System.Int16> value);
        partial void OnIOCOUNT_R2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ControllerCompanyLocationID
        {
            get
            {
                return _ControllerCompanyLocationID;
            }
            set
            {
                OnControllerCompanyLocationIDChanging(value);
                ReportPropertyChanging("ControllerCompanyLocationID");
                _ControllerCompanyLocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerCompanyLocationID");
                OnControllerCompanyLocationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ControllerCompanyLocationID;
        partial void OnControllerCompanyLocationIDChanging(Nullable<global::System.Int32> value);
        partial void OnControllerCompanyLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EmployeemasterID
        {
            get
            {
                return _EmployeemasterID;
            }
            set
            {
                OnEmployeemasterIDChanging(value);
                ReportPropertyChanging("EmployeemasterID");
                _EmployeemasterID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeemasterID");
                OnEmployeemasterIDChanged();
            }
        }
        private Nullable<global::System.Int64> _EmployeemasterID;
        partial void OnEmployeemasterIDChanging(Nullable<global::System.Int64> value);
        partial void OnEmployeemasterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> INOUTDATE_R2
        {
            get
            {
                return _INOUTDATE_R2;
            }
            set
            {
                OnINOUTDATE_R2Changing(value);
                ReportPropertyChanging("INOUTDATE_R2");
                _INOUTDATE_R2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INOUTDATE_R2");
                OnINOUTDATE_R2Changed();
            }
        }
        private Nullable<global::System.DateTime> _INOUTDATE_R2;
        partial void OnINOUTDATE_R2Changing(Nullable<global::System.DateTime> value);
        partial void OnINOUTDATE_R2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CanteenMenuCode
        {
            get
            {
                return _CanteenMenuCode;
            }
            set
            {
                OnCanteenMenuCodeChanging(value);
                ReportPropertyChanging("CanteenMenuCode");
                _CanteenMenuCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanteenMenuCode");
                OnCanteenMenuCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _CanteenMenuCode;
        partial void OnCanteenMenuCodeChanging(Nullable<global::System.Int32> value);
        partial void OnCanteenMenuCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CanteenMenuCodeID
        {
            get
            {
                return _CanteenMenuCodeID;
            }
            set
            {
                OnCanteenMenuCodeIDChanging(value);
                ReportPropertyChanging("CanteenMenuCodeID");
                _CanteenMenuCodeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanteenMenuCodeID");
                OnCanteenMenuCodeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CanteenMenuCodeID;
        partial void OnCanteenMenuCodeIDChanging(Nullable<global::System.Int32> value);
        partial void OnCanteenMenuCodeIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartAccessModel", "FK_Transactions_Controllers", "Controller")]
        public Controller Controller
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Controller>("SmartAccessModel.FK_Transactions_Controllers", "Controller").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Controller>("SmartAccessModel.FK_Transactions_Controllers", "Controller").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Controller> ControllerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Controller>("SmartAccessModel.FK_Transactions_Controllers", "Controller");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Controller>("SmartAccessModel.FK_Transactions_Controllers", "Controller", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
